---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: infra
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          env:
            - name: RABBITMQ_DEFAULT_PASS
              value: "123456"
            - name: RABBITMQ_DEFAULT_USER
              value: root
          image: rabbitmq:3.7.28-management-alpine
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: database-vol
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: database-vol
          hostPath:
            path: /data/rabbitmq/database

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  namespace: infra
  name: rabbitmq
spec:
  type: NodePort
  ports:
    - name: "tcp"
      port: 5672
      targetPort: 5672
      nodePort: 30672
    - name: "http"
      port: 15672
      targetPort: 15672
      nodePort: 31672
  selector:
    app: rabbitmq
