#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: infra
#  labels:
#    app: redis

---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: infra
  name: redis-config
data:
  redis-config: |
    dbfilename dump.rdb
    dir /redis/data
    save ""
    requirepass 123456 
    maxmemory 10240mb
    maxmemory-policy allkeys-lru

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.0
          command: ["bash", "-c", "redis-server /redis/etc/redis.conf"]
          env:
            - name: MASTER
              value: "true"
          ports:
            - containerPort: 6379
          resources:
            limits:
              cpu: "0.1"
          volumeMounts:
            - mountPath: /redis/data
              name: data
            - mountPath: /redis/etc
              name: config
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          configMap:
            name: redis-config
            items:
              - key: redis-config
                path: redis.conf

---
kind: Service
apiVersion: v1
metadata:
  namespace: infra
  name: redis
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    app: redis
