# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: zfaka
#   labels:
#     app: zfaka

---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: zfaka
  name: nginx-config
data:
  nginx.conf: |
    worker_processes auto;
    worker_cpu_affinity auto;
    worker_rlimit_nofile 51200;
    events {
        use epoll;
        worker_connections 51200;
        multi_accept off;
        accept_mutex off;
    }
    http {
      include       mime.types;
      default_type  application/octet-stream;

      server_names_hash_bucket_size 128;
      client_header_buffer_size 32k;
      large_client_header_buffers 4 32k;
      client_max_body_size 50m;

      sendfile on;
      sendfile_max_chunk 512k;
      tcp_nopush on;

      keepalive_timeout 60;

      tcp_nodelay on;

      fastcgi_connect_timeout 300;
      fastcgi_send_timeout 300;
      fastcgi_read_timeout 300;
      fastcgi_buffer_size 64k;
      fastcgi_buffers 4 64k;
      fastcgi_busy_buffers_size 128k;
      fastcgi_temp_file_write_size 256k;

      gzip on;
      gzip_min_length  1k;
      gzip_buffers     4 16k;
      gzip_http_version 1.1;
      gzip_comp_level 2;
      gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml application/xml+rss;
      gzip_vary on;
      gzip_proxied   expired no-cache no-store private auth;
      gzip_disable   "MSIE [1-6]\.";

      #limit_conn_zone $binary_remote_addr zone=perip:10m;
      ##If enable limit_conn_zone,add "limit_conn perip 10;" to server section.

      server_tokens off;

      server {
        listen 80 default_server;
        #listen [::]:80 default_server;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";
        root /var/www/html/zfaka/public;
        index index.php;
        server_name _;
    
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }
    
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            include fastcgi_params;
        }

        location = /favicon.ico { access_log off; log_not_found off; }
        location = /robots.txt  { access_log off; log_not_found off; }
      }
    }

---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: zfaka
  name: zfaka
spec:
  selector:
    matchLabels:
      app: zfaka
  replicas: 1
  template:
    metadata:
      labels:
        app: zfaka
    spec:
      containers:
        - name: php-fpm
          image: ccr.ccs.tencentyun.com/fastapp/zfaka:v1.0.0.1966.ec78eb7f
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-www
            - mountPath: /data
              name: data-vol
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/zfaka /var/www/html && chown -R www-data /var/www/html/zfaka && chgrp -R www-data /var/www/html/zfaka && mkdir -p /data/php/session && mkdir -p /data/php/logs && chgrp -R www-data /data/php && chown -R www-data /data/php"]
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 5 && kill -SIGQUIT 1
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: nginx-www
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-config
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - sleep 5 && /usr/sbin/nginx -s quit
      volumes:
        - name: data-vol
          hostPath:
            path: /data
        - name: nginx-www
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
---
kind: Service
apiVersion: v1
metadata:
  namespace: zfaka
  name: zfaka-svc
spec:
  selector:
    app: zfaka
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: zfaka
  name: zfaka-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: getgpt-tls
      hosts:
        - getgpt.bgton.cn
  rules:
    - host: getgpt.bgton.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zfaka-svc
                port:
                  number: 80
